name: Manual
on:
    workflow_dispatch:
        inputs:
            example_input:
                description: 'An example input'
                required: false
                default: 'default value'
                type: string
        
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "The input value is ${{ inputs.example_input }}"
